# Generated by Django 3.0.7 on 2020-09-10 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название склада')),
                ('capacity', models.PositiveIntegerField(max_length=10, verbose_name='Объем склада')),
                ('char_si', models.PositiveIntegerField(max_length=50, verbose_name='Диоксид кремния')),
                ('char_fe', models.PositiveIntegerField(max_length=50, verbose_name='Железо')),
            ],
        ),
        migrations.CreateModel(
            name='Tipper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(default=0, verbose_name='Бортовой номер')),
                ('model', models.CharField(max_length=10, verbose_name='Модель')),
                ('max_weight', models.PositiveIntegerField(default=0, verbose_name='Максимальная грузоподъемность')),
                ('cur_weight', models.PositiveIntegerField(default=0, verbose_name='Текущий вес')),
                ('overload', models.PositiveIntegerField(default=0, verbose_name='Перегрузка')),
                ('coordinates', models.IntegerField(default=0, verbose_name='Координаты')),
            ],
            options={
                'verbose_name': 'Самосвал',
                'verbose_name_plural': 'Самосвалы',
            },
        ),
    ]
