# Generated by Django 3.0.7 on 2020-09-10 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mining', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stock',
            options={'verbose_name': 'Склад', 'verbose_name_plural': 'Склады'},
        ),
        migrations.AlterField(
            model_name='tipper',
            name='coordinates',
            field=models.IntegerField(default=None, verbose_name='Координаты'),
        ),
        migrations.AlterField(
            model_name='tipper',
            name='cur_weight',
            field=models.PositiveIntegerField(default=None, verbose_name='Текущий вес'),
        ),
        migrations.AlterField(
            model_name='tipper',
            name='max_weight',
            field=models.PositiveIntegerField(default=None, verbose_name='Максимальная грузоподъемность'),
        ),
        migrations.AlterField(
            model_name='tipper',
            name='number',
            field=models.PositiveIntegerField(default=None, verbose_name='Бортовой номер'),
        ),
        migrations.AlterField(
            model_name='tipper',
            name='overload',
            field=models.PositiveIntegerField(default=None, verbose_name='Перегрузка'),
        ),
    ]
