# Generated by Django 3.0.7 on 2020-09-10 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mining', '0003_auto_20200910_2242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipper',
            name='coordinates',
            field=models.IntegerField(null=True, verbose_name='Координаты'),
        ),
    ]
