# Generated by Django 3.0.7 on 2020-09-10 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mining', '0004_auto_20200910_2254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipper',
            name='coordinates',
            field=models.IntegerField(blank=True, default=None, verbose_name='Координаты'),
        ),
    ]
