# Generated by Django 3.0.7 on 2020-09-10 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mining', '0005_auto_20200910_2255'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tipper',
            name='coordinates',
        ),
    ]
