# Generated by Django 3.0.7 on 2020-09-10 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mining', '0006_remove_tipper_coordinates'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipper',
            name='coordinates',
            field=models.IntegerField(blank=True, default=None, verbose_name='Координаты'),
        ),
    ]
