# Generated by Django 3.0.7 on 2020-09-10 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mining', '0007_tipper_coordinates'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tipper',
            name='coordinates',
        ),
        migrations.RemoveField(
            model_name='tipper',
            name='cur_weight',
        ),
        migrations.RemoveField(
            model_name='tipper',
            name='max_weight',
        ),
    ]
