# Generated by Django 3.0.7 on 2020-09-10 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mining', '0008_auto_20200910_2305'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipper',
            name='coordinates',
            field=models.IntegerField(blank=True, default=None, verbose_name='Координаты'),
        ),
        migrations.AddField(
            model_name='tipper',
            name='cur_weight',
            field=models.IntegerField(default=None, verbose_name='Текущий вес'),
        ),
        migrations.AddField(
            model_name='tipper',
            name='max_weight',
            field=models.IntegerField(default=None, verbose_name='Максимальная грузоподъемность'),
        ),
    ]
