# Generated by Django 3.0.7 on 2020-09-10 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mining', '0009_auto_20200910_2305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='capacity',
            field=models.PositiveIntegerField(verbose_name='Объем склада'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='char_fe',
            field=models.PositiveIntegerField(blank=True, verbose_name='Железо'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='char_si',
            field=models.PositiveIntegerField(blank=True, verbose_name='Диоксид кремния'),
        ),
    ]
