# Generated by Django 3.0.7 on 2020-09-10 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mining', '0010_auto_20200910_2310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipper',
            name='coordinates',
            field=models.IntegerField(blank=True, verbose_name='Координаты'),
        ),
    ]
