# Generated by Django 3.0.7 on 2020-09-10 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mining', '0012_auto_20200910_2313'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tipper',
            name='coordinates',
        ),
    ]
