# Generated by Django 3.0.7 on 2020-09-10 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mining', '0014_tipper_coordinates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipper',
            name='number',
            field=models.CharField(default=None, max_length=10, verbose_name='Бортовой номер'),
        ),
    ]
