# Generated by Django 3.0.7 on 2020-09-11 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mining', '0016_auto_20200911_1329'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tipper',
            name='char_fe',
        ),
        migrations.RemoveField(
            model_name='tipper',
            name='char_si',
        ),
    ]
