# Generated by Django 3.0.7 on 2020-09-11 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mining', '0017_auto_20200911_1331'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipper',
            name='char_fe',
            field=models.PositiveIntegerField(blank=True, default=None, verbose_name='Железо'),
        ),
        migrations.AddField(
            model_name='tipper',
            name='char_si',
            field=models.PositiveIntegerField(blank=True, default=None, verbose_name='Диоксид кремния'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='capacity',
            field=models.PositiveIntegerField(verbose_name='Объем склада'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='char_fe',
            field=models.PositiveIntegerField(blank=True, verbose_name='Железо'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='char_si',
            field=models.PositiveIntegerField(blank=True, verbose_name='Диоксид кремния'),
        ),
    ]
