# Generated by Django 3.0.7 on 2020-09-11 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mining', '0019_auto_20200911_1331'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='char_fe',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='char_si',
        ),
    ]
