# Generated by Django 3.0.7 on 2020-09-11 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mining', '0022_auto_20200911_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipper',
            name='coordinates',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='Координаты'),
        ),
    ]
