# Generated by Django 3.0.7 on 2020-09-11 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mining', '0023_auto_20200911_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipper',
            name='coordinates',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Координаты'),
        ),
    ]
