# Generated by Django 3.0.7 on 2020-09-12 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mining', '0024_auto_20200911_1522'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='capacity',
        ),
        migrations.AddField(
            model_name='stock',
            name='capacity_after',
            field=models.PositiveIntegerField(blank=True, default=None, null=True, verbose_name='Объем склада после разгрузки'),
        ),
        migrations.AddField(
            model_name='stock',
            name='capacity_before',
            field=models.PositiveIntegerField(default=None, verbose_name='Объем склада до разгрузки'),
        ),
    ]
