# Generated by Django 3.0.7 on 2020-09-12 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mining', '0025_auto_20200912_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='capacity_after',
            field=models.PositiveIntegerField(blank=True, default=models.PositiveIntegerField(default=None, verbose_name='Объем склада до разгрузки'), null=True, verbose_name='Объем склада после разгрузки'),
        ),
    ]
