# Generated by Django 3.0.7 on 2020-09-12 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mining', '0026_auto_20200912_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='capacity_after',
            field=models.PositiveIntegerField(blank=True, default=None, null=True, verbose_name='Объем склада после разгрузки'),
        ),
    ]
