# Generated by Django 3.0.7 on 2020-09-12 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mining', '0027_auto_20200912_1456'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='capacity_show',
            field=models.PositiveIntegerField(blank=True, default=None, editable=False, null=True, verbose_name='До разгрузки'),
        ),
    ]
