# Generated by Django 3.0.7 on 2020-09-17 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mining', '0028_stock_capacity_show'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='capacity_show',
        ),
    ]
