# Generated by Django 3.0.7 on 2020-09-17 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mining', '0029_remove_stock_capacity_show'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='polygon',
            field=models.CharField(default=None, editable=False, max_length=50, verbose_name='Координаты полигона'),
        ),
    ]
