# Generated by Django 3.0.7 on 2020-09-17 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mining', '0031_auto_20200917_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='polygon',
            field=models.CharField(blank=True, default=None, editable=False, max_length=50, null=True, verbose_name='Координаты полигона'),
        ),
    ]
