# Generated by Django 3.0.7 on 2020-09-17 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mining', '0032_auto_20200917_1624'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='polygon',
        ),
    ]
