# Generated by Django 3.0.7 on 2020-09-17 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mining', '0035_auto_20200917_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='capacity_after',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Объем склада после разгрузки'),
        ),
    ]
