# Generated by Django 3.0.7 on 2020-09-17 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mining', '0036_auto_20200917_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='capacity_after',
            field=models.PositiveIntegerField(default=None, verbose_name='Объем склада после разгрузки'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='char_fe',
            field=models.IntegerField(verbose_name='Железо'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='char_si',
            field=models.IntegerField(verbose_name='Диоксид кремния'),
        ),
    ]
