# Generated by Django 3.0.7 on 2020-09-17 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mining', '0038_auto_20200917_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='char_fe',
            field=models.FloatField(verbose_name='Железо'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='char_si',
            field=models.FloatField(verbose_name='Диоксид кремния'),
        ),
    ]
